import numpy as np
from src.models.two_tower import HAS_TORCH

class VectorRetrievalStage:
    def __init__(self, items, two_tower_net, categories=None):
        """
        items: List of item dicts generated by generator.py
        two_tower_net: TwoTowerNet (PyTorch or NumPy fallback wrapper)
        """
        self.items = items
        self.two_tower_net = two_tower_net
        if categories is None:
            categories = ['Cyberwear', 'Implants', 'Holo-Tech', 'Software']
        self.categories = categories
        
        # Precompute and cache normalized item embedding vectors to simulate FAISS index!
        self.item_ids = [it['id'] for it in items]
        self.cached_item_vectors = []
        
        self._build_vector_index()
        
    def _build_vector_index(self):
        """
        Runs item embeddings through ItemTower and caches the normalized outputs
        """
        for it in self.items:
            cat_idx = self.categories.index(it['category'])
            base_emb = it['embedding']
            
            # Map embedding through ItemTower projection
            if hasattr(self.two_tower_net, 'item_tower'):
                # Handle PyTorch model versus NumPy Fallback
                if HAS_TORCH:
                    import torch
                    with torch.no_grad():
                        emb_t = torch.tensor([base_emb], dtype=torch.float32)
                        cat_t = torch.tensor([cat_idx], dtype=torch.long)
                        item_vec = self.two_tower_net.item_tower(emb_t, cat_t).numpy()[0]
                else:
                    item_vec = self.two_tower_net.item_tower.forward(base_emb, cat_idx)
            else:
                # If simplified NumPy wrapper
                item_vec = base_emb
                
            self.cached_item_vectors.append(item_vec)
            
        self.cached_item_vectors = np.array(self.cached_item_vectors) # [NumItems, LatentDim]

    def retrieve_candidates(self, user_profile, top_k=100):
        """
        Computes user embedding and performs dot-product candidate retrieval
        """
        base_user_emb = user_profile['embedding']
        age_idx = [18, 24, 30, 35, 45].index(user_profile['age'])
        device_idx = ['Neural Jack', 'Cyborg Deck', 'Holo Glass'].index(user_profile['device'])
        
        # 1. Project user features to latent vector space
        if hasattr(self.two_tower_net, 'user_tower'):
            if HAS_TORCH:
                import torch
                with torch.no_grad():
                    emb_t = torch.tensor([base_user_emb], dtype=torch.float32)
                    age_t = torch.tensor([age_idx], dtype=torch.long)
                    dev_t = torch.tensor([device_idx], dtype=torch.long)
                    user_vec = self.two_tower_net.user_tower(emb_t, age_t, dev_t).numpy()[0]
            else:
                user_vec = self.two_tower_net.user_tower.forward(base_user_emb, age_idx, device_idx)
        else:
            user_vec = base_user_emb
            
        user_vec = np.array(user_vec) # [LatentDim]
        
        # 2. Vector search: Dot product with all cached items
        similarities = np.dot(self.cached_item_vectors, user_vec) # [NumItems]
        
        # 3. Sort indices descending
        top_indices = np.argsort(similarities)[::-1][:top_k]
        
        candidates = []
        for idx in top_indices:
            item = dict(self.items[idx])
            # Store calculated similarity vector score
            item['embedding'] = self.cached_item_vectors[idx].tolist()
            item['base_similarity'] = float(similarities[idx])
            candidates.append(item)
            
        return candidates, user_vec.tolist()
